/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gin Kern Creative Cloud (https://sketchfab.com/GinKern)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/studio-office-interior-57988c1c4c6e4bfc9e1f0e00ac080844
Title: Studio  Office  Interior
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import OfficeScene from '../../assets/3d/studio__office__interior (1).glb'
import { a } from '@react-spring/three'

const Office = (props) => {
    const { nodes, materials } = useGLTF(OfficeScene)
    const officeRef = useRef()
    return (
        <a.group {...props} ref={officeRef}>
            <group scale={0.01}>
                <group scale={100}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
                        <group rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes.Cube__0_1.geometry}
                                material={materials.Cube__0}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={100}
                            />
                            <mesh
                                geometry={nodes.Plane_002_White_0_1.geometry}
                                material={materials.White}
                                rotation={[Math.PI, 0, 0]}
                                scale={[264.514, 195.858, 100]}
                            />
                            <group
                                position={[-123.493, 1.133, 64.664]}
                                rotation={[-Math.PI / 2, 0, -2.988]}
                                scale={100}>
                                <mesh
                                    geometry={nodes.Archinteriors8_01_292_003_Material_004_0_1.geometry}
                                    material={materials.Material_004}
                                />
                                <mesh
                                    geometry={nodes.Archinteriors8_01_292_003_Esmalte_Preto_001_0_1.geometry}
                                    material={materials.Esmalte_Preto_001}
                                />
                            </group>
                            <group
                                position={[83.984, 227.115, 272.869]}
                                rotation={[-Math.PI / 2, 0, -Math.PI]}
                                scale={109.963}>
                                <mesh


                                    geometry={nodes.books_005_books_003_0_1.geometry}
                                    material={materials.books_003}
                                />
                                <mesh


                                    geometry={nodes.books_005_books_paper_002_0_1.geometry}
                                    material={materials.books_paper_002}
                                />
                            </group>
                            <group
                                position={[108.26, 44.492, -116.527]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[4.659, 3.09, 3.015]}>
                                <mesh


                                    geometry={nodes.Box323536_001_Cabinet_color_001_0_1.geometry}
                                    material={materials.Cabinet_color_001}
                                />
                                <mesh


                                    geometry={nodes.Box323536_001_Cabinet_Wood_001_0_1.geometry}
                                    material={materials.Cabinet_Wood_001}
                                />
                                <mesh


                                    geometry={nodes.Box323536_001_Cabinet_Handle_001_0_1.geometry}
                                    material={materials.Cabinet_Handle_001}
                                />
                            </group>
                            <group
                                position={[-39.701, 109.763, 134.386]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.178}>
                                <mesh


                                    geometry={nodes.Circle_001_PC1GlossyPin_001_0_1.geometry}
                                    material={materials.PC1GlossyPin_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1WireInGlas_0_1.geometry}
                                    material={materials.PC1WireInGlas}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1PenGlossyPart1_001_0_1.geometry}
                                    material={materials.PC1PenGlossyPart1_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1PenBlackpart_001_0_1.geometry}
                                    material={materials.PC1PenBlackpart_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1Material_009_0_1.geometry}
                                    material={materials.PC1Material_009}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1Material_008_0_1.geometry}
                                    material={materials.PC1Material_008}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1Material_015_0_1.geometry}
                                    material={materials.PC1Material_015}
                                />
                                <mesh


                                    geometry={nodes.Circle_001_PC1Material_016_0_1.geometry}
                                    material={materials.PC1Material_016}
                                />
                            </group>
                            <group
                                position={[6.5, 109.763, -135.082]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.178}>
                                <mesh


                                    geometry={nodes.Circle_002_PC1GlossyPin_001_0_1.geometry}
                                    material={materials.PC1GlossyPin_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1WireInGlas_0_1.geometry}
                                    material={materials.PC1WireInGlas}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1PenGlossyPart1_001_0_1.geometry}
                                    material={materials.PC1PenGlossyPart1_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1PenBlackpart_001_0_1.geometry}
                                    material={materials.PC1PenBlackpart_001}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1Material_009_0_1.geometry}
                                    material={materials.PC1Material_009}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1Material_008_0_1.geometry}
                                    material={materials.PC1Material_008}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1Material_015_0_1.geometry}
                                    material={materials.PC1Material_015}
                                />
                                <mesh


                                    geometry={nodes.Circle_002_PC1Material_016_0_1.geometry}
                                    material={materials.PC1Material_016}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Cube_001_Light_Fixture_0_1.geometry}
                                material={materials.Light_Fixture}
                                position={[-243.376, 374.575, -81.939]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[17.475, 221.057, 14.36]}
                            />
                            <group
                                position={[414.959, 364.929, 481.161]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={5.07}>
                                <mesh


                                    geometry={nodes.Cylinder_Inner_Light_case_0_1.geometry}
                                    material={materials.Inner_Light_case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_Inner_light_emission_0_1.geometry}
                                    material={materials.Inner_light_emission}
                                />
                            </group>
                            <group
                                position={[-0.475, 364.929, -79.019]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_001_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_001_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[-244.636, 364.929, -79.019]}
                                rotation={[-Math.PI / 2, -0.322, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_002_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_002_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[243.686, 364.929, -79.019]}
                                rotation={[-Math.PI / 2, 0.291, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_003_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_003_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[-244.636, 364.929, 122.199]}
                                rotation={[-Math.PI / 2, -0.211, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_004_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_004_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[-0.475, 364.929, 122.199]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_005_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_005_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[243.686, 364.929, 122.199]}
                                rotation={[-1.465, 0.287, -0.38]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_006_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_006_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[-244.636, 364.929, -285.145]}
                                rotation={[-Math.PI / 2, -0.339, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_007_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_007_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[-0.475, 364.929, -285.145]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_008_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_008_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <group
                                position={[243.686, 364.929, -285.145]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={7.313}>
                                <mesh


                                    geometry={nodes.Cylinder_009_Light_Case_0_1.geometry}
                                    material={materials.Light_Case}
                                />
                                <mesh


                                    geometry={nodes.Cylinder_009_Light_emission_0_1.geometry}
                                    material={materials.Light_emission}
                                />
                            </group>
                            <mesh


                                geometry={nodes.low_poly_001_PC2_CUP_0_1.geometry}
                                material={materials.PC2_CUP}
                                position={[-96.934, 104.672, -179.34]}
                                rotation={[Math.PI, -1.218, Math.PI]}
                                scale={104.361}
                            />
                            <mesh


                                geometry={nodes.low_poly_012_Black5_001_0_1.geometry}
                                material={materials.Black5_001}
                                position={[89.963, 21.688, 0]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={100}
                            />
                            <mesh


                                geometry={nodes.low_poly_013_Green1_0_1.geometry}
                                material={materials.Green1}
                                position={[89.963, 21.688, 0]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={100}
                            />
                            <mesh


                                geometry={nodes.low_poly_014_Black5_0_1.geometry}
                                material={materials.PC1WireInGlas}
                                position={[928.261, 144.487, -287.716]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={100}
                            />
                            <mesh


                                geometry={nodes.low_poly_018_PC2_CUP_0_1.geometry}
                                material={materials.PC2_CUP}
                                position={[-96.934, 104.672, -9.247]}
                                rotation={[Math.PI, -1.218, Math.PI]}
                                scale={104.361}
                            />
                            <mesh


                                geometry={nodes.low_poly_025_Blue3_0_1.geometry}
                                material={materials.Blue3}
                                position={[89.963, 21.688, 0]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={100}
                            />
                            <mesh


                                geometry={nodes.Mirror_Chrome_001_0_1.geometry}
                                material={materials.Chrome_001}
                                position={[114.094, 229.585, 423.474]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[88.69, 71.932, 71.932]}
                            />
                            <mesh


                                geometry={nodes.Monitor_27__Curved_001_PC1MOUSE_PAD_0_1.geometry}
                                material={materials.PC1MOUSE_PAD}
                                position={[-98.322, 98.079, 66.16]}
                                rotation={[Math.PI, 0.004, -Math.PI]}
                                scale={4.887}
                            />
                            <group
                                position={[-53.651, 132.925, 46.362]}
                                rotation={[Math.PI, 0.004, -Math.PI]}
                                scale={4.887}>
                                <mesh


                                    geometry={nodes.Monitor_27__Curved_002_PC_1Back_Panel_0_1.geometry}
                                    material={materials.PC_1Back_Panel}
                                />
                                <mesh


                                    geometry={nodes.Monitor_27__Curved_002_PC_1Wallpaper_0_1.geometry}
                                    material={materials.PC_1Wallpaper}
                                />
                                <mesh


                                    geometry={nodes.Monitor_27__Curved_002_PC_1Stand_0_1.geometry}
                                    material={materials.PC_1Stand}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Monitor_27__Curved_003_PC_1_Keyboard_0_1.geometry}
                                material={materials.PC_1_Keyboard}
                                position={[-100.191, 98.17, 38.896]}
                                rotation={[Math.PI, 0.004, -Math.PI]}
                                scale={4.887}
                            />
                            <mesh


                                geometry={nodes.Monitor_27__Curved_004_PC1MOUSE_0_1.geometry}
                                material={materials.PC1MOUSE}
                                position={[-98.322, 98.079, 66.16]}
                                rotation={[Math.PI, 0.004, -Math.PI]}
                                scale={4.887}
                            />
                            <mesh


                                geometry={nodes.Plane_Material_003_0_1.geometry}
                                material={materials.Material_003}
                                position={[1.104, 94.98, -60.764]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[129.712, 201.896, 100]}
                            />
                            <mesh


                                geometry={nodes.Plane_003_Black_Frame_Window_0_1.geometry}
                                material={materials.Black_Frame_Window}
                                position={[-291.837, 406.102, -729.952]}
                                scale={[39.626, 43.596, 41.484]}
                            />
                            <mesh


                                geometry={nodes.Plane_005_Black_Frame_Window_0_1.geometry}
                                material={materials.Black_Frame_Window}
                                position={[530.865, 406.102, -594.362]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[39.626, 43.596, 27.591]}
                            />
                            <group
                                position={[520.768, 213.61, -608.052]}
                                rotation={[0, -Math.PI / 2, 0]}
                                scale={[48.538, 41.777, 39.57]}>
                                <mesh


                                    geometry={nodes.Plane_006_Black_Frame_Window_0_1.geometry}
                                    material={materials.Black_Frame_Window}
                                />
                                <mesh


                                    geometry={nodes.Plane_006_Window_Glass_0_1.geometry}
                                    material={materials.Window_Glass}
                                />
                            </group>
                            <group
                                position={[0, 0, -100.308]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[515.103, 398.369, 398.369]}>
                                <mesh


                                    geometry={nodes.Plane_007_Material_002_0_1.geometry}
                                    material={materials.Material_002}
                                />
                                <mesh


                                    geometry={nodes.Plane_007_Material_008_0_1.geometry}
                                    material={materials.Material_008}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Plane_008_Black_Frame_Window_0_1.geometry}
                                material={materials.Black_Frame_Window}
                                position={[-530.479, 392.357, 433.823]}
                                rotation={[0, -Math.PI / 2, 0]}
                                scale={[39.626, 43.596, 27.591]}
                            />
                            <group
                                position={[-520.382, 199.865, 447.513]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[48.538, 41.777, 39.57]}>
                                <mesh


                                    geometry={nodes.Plane_009_Black_Frame_Window_0_1.geometry}
                                    material={materials.Black_Frame_Window}
                                />
                                <mesh


                                    geometry={nodes.Plane_009_Window_Glass_0_1.geometry}
                                    material={materials.Window_Glass}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Plane_010_Black_Frame_Window_0_1.geometry}
                                material={materials.Black_Frame_Window}
                                position={[-506.293, 406.102, -122.885]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[39.626, 43.596, 41.484]}
                            />
                            <mesh


                                geometry={nodes.Plane_011_Black_Frame_Window_0_1.geometry}
                                material={materials.Black_Frame_Window}
                                position={[539.604, 204.942, 441.675]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[39.626, 43.596, 27.591]}
                            />
                            <group
                                position={[543.958, 172.648, 409.438]}
                                rotation={[0, -Math.PI / 2, 0]}
                                scale={[48.538, 41.777, 39.57]}>
                                <mesh


                                    geometry={nodes.Plane_012_Black_Frame_Window_0_1.geometry}
                                    material={materials.Black_Frame_Window}
                                />
                                <mesh


                                    geometry={nodes.Plane_012_Bathroom_door_opaque_0_1.geometry}
                                    material={materials.Bathroom_door_opaque}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Plane_013_Floor_0_1.geometry}
                                material={materials.Floor}
                                position={[0, 1.545, -100.308]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={103.318}
                            />
                            <mesh


                                geometry={nodes.Plane_014_Material_002_0_1.geometry}
                                material={materials.Material_002}
                                position={[0, 0, -100.308]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[515.103, 398.369, 398.369]}
                            />
                            <group position={[0, 0, -100.308]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                <mesh


                                    geometry={nodes.Plane_015_Wall_0_1.geometry}
                                    material={materials.Wall}
                                />
                                <mesh


                                    geometry={nodes.Plane_015_Wall_Rim_0_1.geometry}
                                    material={materials.Wall_Rim}
                                />
                            </group>
                            <group
                                position={[-522.979, 196.332, -25.769]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={[48.538, 41.777, 39.57]}>
                                <mesh


                                    geometry={nodes.Plane_020_Black_Frame_Window_0_1.geometry}
                                    material={materials.Black_Frame_Window}
                                />
                                <mesh


                                    geometry={nodes.Plane_020_Window_Glass_0_1.geometry}
                                    material={materials.Window_Glass}
                                />
                            </group>
                            <group
                                position={[87.241, 97.398, 7.543]}
                                rotation={[-Math.PI / 2, 0, 1.834]}
                                scale={1.237}>
                                <mesh


                                    geometry={nodes.R_Mouse_00_001_PC2_BODY_0_1.geometry}
                                    material={materials.PC2_BODY}
                                />
                                <mesh


                                    geometry={nodes.R_Mouse_00_001_PC2_SCREEN_0_1.geometry}
                                    material={materials.PC2_SCREEN}
                                />
                            </group>
                            <mesh


                                geometry={nodes.R_Mouse_00_002_PC2_MOUSEPAD_0_1.geometry}
                                material={materials.PC2_MOUSEPAD}
                                position={[92.88, 98.081, 42.961]}
                                rotation={[-Math.PI / 2, 0, 1.834]}
                                scale={1.237}
                            />
                            <mesh


                                geometry={nodes.R_Mouse_00_003_PC2_KEYBOARD_0_1.geometry}
                                material={materials.PC2_KEYBOARD}
                                position={[94.34, 98.17, 59.888]}
                                rotation={[-Math.PI / 2, 0, 1.834]}
                                scale={1.237}
                            />
                            <mesh


                                geometry={nodes.R_Mouse_00_004_PC2_MOUSE_0_1.geometry}
                                material={materials.PC2_MOUSE}
                                position={[92.88, 98.081, 42.961]}
                                rotation={[-Math.PI / 2, 0, 1.834]}
                                scale={1.237}
                            />
                            <group
                                position={[165.531, 135.211, 385.731]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={43.618}>
                                <mesh


                                    geometry={nodes.Rectangle013_001_Marble_0_1.geometry}
                                    material={materials.Marble}
                                />
                                <mesh


                                    geometry={nodes.Rectangle013_001_Chrome_0_1.geometry}
                                    material={materials.Chrome}
                                />
                                <mesh


                                    geometry={nodes.Rectangle013_001_Material_020_0_1.geometry}
                                    material={materials.Material_020}
                                />
                                <mesh


                                    geometry={nodes.Rectangle013_001_Material_055_0_1.geometry}
                                    material={materials.Material_055}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Soap_1_Cylinder_001_bottle_base_0_1.geometry}
                                material={materials.bottle_base}
                                position={[141.075, 156.257, 454.893]}
                                rotation={[Math.PI, 0.526, -Math.PI]}
                                scale={11.088}
                            />
                            <mesh


                                geometry={nodes.Soap_2_Cylinder_001_bottle_top_0_1.geometry}
                                material={materials.bottle_top}
                                position={[142.89, 167.136, 455.22]}
                                rotation={[Math.PI, 0.526, -Math.PI]}
                                scale={11.088}
                            />
                            <group
                                position={[56.094, 110.061, -259.265]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={1.702}>
                                <mesh


                                    geometry={nodes.surface_SURFACE_2_SCREEN_0_1.geometry}
                                    material={materials.SURFACE_2_SCREEN}
                                />
                                <mesh


                                    geometry={nodes.surface_SURFACE_2_KEYBOARD_0_1.geometry}
                                    material={materials.SURFACE_2_KEYBOARD}
                                />
                            </group>
                            <group
                                position={[56.094, 110.061, -259.265]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={1.702}>
                                <mesh


                                    geometry={nodes.surface_001_SURFACE_1_SCREEN_0_1.geometry}
                                    material={materials.SURFACE_1_SCREEN}
                                />
                                <mesh


                                    geometry={nodes.surface_001_SURFACE_1_KEYBOARD_0_1.geometry}
                                    material={materials.PC1WireInGlas}
                                />
                            </group>
                            <group
                                position={[-91.47, 95.896, -232.847]}
                                rotation={[-1.596, 0.245, -1.468]}
                                scale={41.664}>
                                <mesh


                                    geometry={nodes.tela_LAP_1_BODY_0_1.geometry}
                                    material={materials.LAP_1_BODY}
                                />
                                <mesh


                                    geometry={nodes.tela_LAP_1_BLACK_FRAME_0_1.geometry}
                                    material={materials.LAP_1_BLACK_FRAME}
                                />
                                <mesh


                                    geometry={nodes.tela_LAP_1SCREEN_0_1.geometry}
                                    material={materials.LAP_1SCREEN}
                                />
                                <mesh


                                    geometry={nodes.tela_LAP_1_KEYBOARD_0_1.geometry}
                                    material={materials.LAP_1_KEYBOARD}
                                />
                            </group>
                            <group
                                position={[364.786, 174.615, 561.623]}
                                rotation={[0, 1.571, 0]}
                                scale={[110.631, 153.836, 110.631]}>
                                <mesh


                                    geometry={nodes.wall_pictures_001_Other_BUddha_frame_0_1.geometry}
                                    material={materials.Other_BUddha_frame}
                                />
                                <mesh


                                    geometry={nodes.wall_pictures_001_Other_BUdhha_001_0_1.geometry}
                                    material={materials.Other_BUdhha_001}
                                />
                            </group>
                            <group
                                position={[512.488, 226.051, -221.782]}
                                rotation={[Math.PI, 0, Math.PI]}
                                scale={[119.579, 166.278, 119.579]}>
                                <mesh


                                    geometry={nodes.wall_pictures_003_Other_BUddha_frame_0_1.geometry}
                                    material={materials.Other_BUddha_frame}
                                />
                                <mesh


                                    geometry={nodes.wall_pictures_003_Other_BUdhha_0_1.geometry}
                                    material={materials.Other_BUdhha}
                                />
                            </group>
                            <group position={[-388.953, 196.332, -746.637]} scale={[48.538, 41.777, 39.57]}>
                                <mesh


                                    geometry={nodes.Plane_004_Black_Frame_Window_001_0_1.geometry}
                                    material={materials.Black_Frame_Window}
                                />
                                <mesh


                                    geometry={nodes.Plane_004_Window_Glass_001_0_1.geometry}
                                    material={materials.Window_Glass_001}
                                />
                            </group>
                            <mesh


                                geometry={nodes.Plane_001_Roof_0_1.geometry}
                                material={materials.Roof}
                                position={[-21.744, 363.68, -65.287]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={105.553}
                            />
                            <mesh


                                geometry={nodes.Plane_016_Material_001_0_1.geometry}
                                material={materials.Material_001}
                                position={[2.5, 2.508, -554.031]}
                                rotation={[-Math.PI / 2, 0, 0]}
                                scale={[106.229, 170.858, 100]}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </a.group>
    )
}

export default Office